from django.contrib.auth import get_user_modelfrom django.core.exceptions import ValidationErrorfrom djoser.serializers import UserCreateSerializerUser = get_user_model()class CustomUserCreateSerializer(UserCreateSerializer):    class Meta(UserCreateSerializer.Meta):        model = User        fields = ('email', 'first_name', 'last_name', 'user_phone',                  'password', 'about_me', 'profile_picture', 'roles')    def create(self, validated_data):        roles = validated_data.pop('roles', [])        user = super().create(validated_data)        for role in roles:            try:                user.add_role(role.name)            except ValidationError as e:                raise ValidationError(f"Failed to add role '{role.name}': {e}")        return user